[package]
name = "noti-api"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
noti-core.workspace = true
noti-protocol.workspace = true
noti-logic.workspace = true

connectrpc.workspace = true
buffa.workspace = true
axum.workspace = true

serde_json.workspace = true
uuid.workspace = true
tracing.workspace = true
